<?php
/**
 *
 */

//Who is going to get the data from contact form
define('MAIL_RECIPIENT','jovanny.zepeda@corb.mx');


//STMP to use for send mail in contact form
// sets GMAIL as the SMTP server
define('SMTP_HOST','smtp.gmail.com');
// enable SMTP authentication
define('SMTP_AUTH','true');
// sets the prefix to the servier
define('SMTP_SECURE','tls');
// set the SMTP port for the GMAIL server
define('SMTP_PORT','587');
// GMAIL username
define('SMTP_USERNAME','vivesolar.mx@gmail.com');
// GMAIL password
define('SMTP_PASSWORD','vivesolarmx');  




